use std::collections::{HashSet, HashMap};

mod tests;

#[derive(Debug, PartialEq)]
enum Color { Black, White }

#[derive(Debug, PartialEq)]
enum Direction { East, SouthEast, SouthWest, West, NorthWest, NorthEast }

fn parse_tile_directions(directions: &str) -> Vec<Direction> {
    let mut parsed_directions = vec![];

    let mut iter = directions.chars();
    loop {
        let c = iter.next();
        if c.is_none() {
            break;
        }

        let c = c.unwrap();

        parsed_directions.push(
            match c {
                'e' => Direction::East,
                'w' => Direction::West,
                's' => {
                    match iter.next().unwrap() {
                        'e' => Direction::SouthEast,
                        _ => Direction::SouthWest
                    }
                }
                _ => {
                    match iter.next().unwrap() {
                        'e' => Direction::NorthEast,
                        _ => Direction::NorthWest
                    }
                }
            }
        );
    }

    parsed_directions
}

#[derive(Debug, PartialEq, Hash, Eq)]
struct HexCoord {
    col: i32,
    row: i32,
}

impl HexCoord {
    pub fn new(col: i32, row: i32) -> HexCoord {
        HexCoord { col, row }
    }
}

/*
We use "Doubled coordinates" (https://www.redblobgames.com/grids/hexagons/) to represent our grid.
 */
fn get_neighbour_in_direction(from: &HexCoord, in_direction: &Direction) -> HexCoord {
    let (d_col, d_row) = match in_direction {
        Direction::East => (2, 0),
        Direction::SouthEast => (1, 1),
        Direction::SouthWest => (-1, 1),
        Direction::West => (-2, 0),
        Direction::NorthWest => (-1, -1),
        Direction::NorthEast => (1, -1)
    };

    HexCoord::new(from.col + d_col, from.row + d_row)
}

fn tile_direction_input_to_coords(input: &str) -> HexCoord {
    let instructions = parse_tile_directions(input);
    let mut current_tile_coordinates = HexCoord::new(0, 0);

    for instruction in instructions.iter() {
        current_tile_coordinates = get_neighbour_in_direction(&current_tile_coordinates, instruction);
    }

    current_tile_coordinates
}

#[derive(Debug)]
struct Grid {
    grid: HashMap<HexCoord, Color>
}

impl Grid {
    pub fn new() -> Grid {
        Grid { grid: HashMap::new() }
    }
}

fn solve1(input: &Vec<String>) -> usize {
    let mut flipped_tiles: HashSet<HexCoord> = HashSet::new();

    for instruction in input.iter() {
        let tile_coords = tile_direction_input_to_coords(&instruction);

        if flipped_tiles.contains(&tile_coords) {
            flipped_tiles.remove(&tile_coords);
        } else {
            flipped_tiles.insert(tile_coords);
        }
    }

    flipped_tiles.len()
}

fn get_input() -> Vec<String> {
    vec![
        String::from("swsenenwneswnewseswwseswnwsweeswnw"),
        String::from("esweeeeneeeneeeweeeenenenee"),
        String::from("ewewsewswnewnwnewwwwsew"),
        String::from("nwnwnwnwnenwwnwsenwnwnwnwnwnwnw"),
        String::from("nwswseswneswseswswneswswseneseswswsenwswse"),
        String::from("swswswneswswswswwneseswwswsw"),
        String::from("newnwwnwnenenenenwsweenenwnenwnenese"),
        String::from("senwsewseneneseneenenwwneneeswnewsw"),
        String::from("eeeeneweeeseeeeeenewneswe"),
        String::from("wnwswwewwwsewnwnwwnwnwwwnwnwnww"),
        String::from("nenwnwnwnesenwwnwnwwneswnwnenesweneenwnw"),
        String::from("nwwnwwwwenwwswnwwwwwewsesew"),
        String::from("swnwswwswswewswseswnwne"),
        String::from("wswnewswnwwwwenewsewwwwneswe"),
        String::from("nwnwnenenewneneneneneenenesenwneswneswse"),
        String::from("nwewsenwnwneseswwwwwwswwswwwwe"),
        String::from("nesenwseneswseswnwneseseseseseswnwse"),
        String::from("wnesweseswenwnenwnweseeseseeswnwse"),
        String::from("swswnenenenenewneneeeneneeneneenenene"),
        String::from("seseseseeweseeesee"),
        String::from("wwwwwwwwwnewnwwwswww"),
        String::from("sesenwesenwseeseseseewswneseseesesw"),
        String::from("wnewwwsewnwwnwnwewnwswnwwwwnwe"),
        String::from("nwnwnenwnwneneenewswnwnenwswnwnesenwsw"),
        String::from("eeswwneeneneeneeneeeeesw"),
        String::from("seneenesewneeneswwnenenweeenenewwe"),
        String::from("seswseswsenwswswseswswswswenwswsesesw"),
        String::from("nwnwnenwnenwnenwnwnwnenwswnenwwwnwese"),
        String::from("wnwwwwwnwwwnwwnwnwseneenwnwnww"),
        String::from("ewnwnwnwnwnwnenwnwnwnenenwsenenwnwnene"),
        String::from("neneweeeeneeneesweseswswneseswse"),
        String::from("seswseeneswswswseseewsewnwswswwnwne"),
        String::from("swwneneneweseswnenwneeneneeeeeeee"),
        String::from("swwwwwwwwwwwwswswwswswnesew"),
        String::from("eewenwseeeeeweeeeneeese"),
        String::from("neneneneneeneswneeenee"),
        String::from("sewnwnwwswnwseenwwnenenwwnw"),
        String::from("swsweswswswswsewseneseswswsesweswnwsw"),
        String::from("nenewewwwwwwwwwnewwswsesewww"),
        String::from("enwsweneseseeesese"),
        String::from("swneseseseneeseesenwwseneswseseseseew"),
        String::from("nwswswneeeewneseenwnwnesewwswnwesw"),
        String::from("nenenwneenwneneneneneneneneneswenewne"),
        String::from("nwneneseeenwnwnwneneneswneswwnenwnwnenw"),
        String::from("neseenenwneeneneneeeeneene"),
        String::from("sesesewseseseswneseesesesesenewseswsese"),
        String::from("senwnewseneneeeneeeeeenesenwnene"),
        String::from("eeweneneeenweeeseesweeeee"),
        String::from("esesenwswnwseewseswseeeseswenenwse"),
        String::from("neeneeeseswseeesweneeseeesweee"),
        String::from("swweswnwneswswwswswneswswswswswsw"),
        String::from("wwswwwnwnwnenewnwenwswnwsesenwnwe"),
        String::from("neseneenwneeeeeneneeeewneeene"),
        String::from("swsenwsesesweswsewswswswsenwneseswsesw"),
        String::from("wewwwwwnwwwwwnwwwnw"),
        String::from("swseweeenwswneseseesenese"),
        String::from("senwsesesesesesesewseesewe"),
        String::from("sewnwnwnweswnwnwsenwnwnwnwsenwnwnwnwnw"),
        String::from("swswswswswswswswswseswswswswswswwswnesw"),
        String::from("wswnwnwsewwnwewwewwnesewwne"),
        String::from("enenenwnewnenwnenenwwneswneseswnenwsenwnw"),
        String::from("seseseswswseswsewnwsewswswseeseeswse"),
        String::from("nwseswnweswnwneseweswsesweseseswne"),
        String::from("seseswwnwswneneseneneseeseesenwswnwww"),
        String::from("wswswwwwswwneswseswnwswswsew"),
        String::from("senwnwwnwnwesewswnewswwsenwwnwnwwnw"),
        String::from("swsewneswswswswwswswwswswswsw"),
        String::from("eneseeeswneswneeseesenwewsenwewnwnw"),
        String::from("neneneeeneweneneeswe"),
        String::from("neeeseeenwnweewswnewneseneenenee"),
        String::from("senewesesenweseseeesewsesesesesesee"),
        String::from("eseeeseseseenwseeneseseeewse"),
        String::from("nwnwseseenwenwnenwwswnwnwnwwnwnwnwnwnw"),
        String::from("senewweseeenwsesesenesewsesesesee"),
        String::from("enenenwswnenewswenwnwneenwwnwswnenene"),
        String::from("eswseseneswsenwswseseseswsesesewsenwsesee"),
        String::from("wnwneswneseneneneneeneneswenenenenewne"),
        String::from("seswneewsenesesewnwwswnesewswesenwne"),
        String::from("eswwesenwwenwnwnweseseeeeeese"),
        String::from("neeneswneeswnenesenwnwneswnenwneneswsene"),
        String::from("swswneseseswswswswwewnwsenwesweneswnwe"),
        String::from("nwenwwwnwnwnenwnenwnwnwnwnwsweneswe"),
        String::from("seseneneeseseeeeswsenwwwesesenwe"),
        String::from("sweswseswwnwsesesewseseseseswseneswnene"),
        String::from("seswseseseseseswwseswsenesesesesesesese"),
        String::from("sesesenwswswseswswsw"),
        String::from("senwseeeeseseeseseseenwewswesee"),
        String::from("wwsenwewwnewwswwwwwswwwwwne"),
        String::from("nwnwnwneswnwnwnwsenwwwnwwnwnwnwenwse"),
        String::from("swwwswswswwwsewnenwswwswwswseww"),
        String::from("enweenesesesenewnwnwwswswswseseese"),
        String::from("swnenenenenenenenwnenesenewnenwnenenwnene"),
        String::from("enenesweeeeseneeneeeneeneeew"),
        String::from("wnweseeswnwwenwnenwnwnwwenwnwsenwwnw"),
        String::from("neswswswseswswswwswnesw"),
        String::from("neswseeneseswsewseseswseseswswwswswse"),
        String::from("seeneswsesenweeeseeseswsewenesee"),
        String::from("wewewwnenesewsenwwnenwnwseswsww"),
        String::from("nwnwsesewnwseeeswnwnwseewseenw"),
        String::from("nwwwwwnwwnwnwwwwnwsenwwwwsew"),
        String::from("eenwneseeeneeneenenwseeeeeee"),
        String::from("nwenwnwnenwswnwneesenwwwnwnwnwsenwnw"),
        String::from("swswswswseswswswswwseswswswswswswswswne"),
        String::from("swwwwwwwwwwnwwewwwnwwww"),
        String::from("esweeeeeeneeenwnwenesw"),
        String::from("eeenweeeseese"),
        String::from("wwwnewwsewewwwwwwwwww"),
        String::from("seseseeseseesesenwesewseeseseseswnesese"),
        String::from("senwnwwneswwswwnenwwwewnwnwwnww"),
        String::from("swnwsesewneenwenwseenwneeseeseewsw"),
        String::from("eneeneneneneneneswsewswsenenenwnenenenw"),
        String::from("wneesweseswswwsewswnweswswewswswse"),
        String::from("neseneneeewneneenewnenenenenenenenene"),
        String::from("wswnesewwsenewswswswswneswswswsweesw"),
        String::from("swswsesenwseswsewseswneseseseswsesw"),
        String::from("seswwswwwseswswswswswweswneswswnewsww"),
        String::from("neneesenewewnenwneneneswnwweswswnese"),
        String::from("swswswwwswswswswswwneswswwwswseww"),
        String::from("neenenenenenenenenenwsewneneneneswnenene"),
        String::from("eneeeeseenenwwesenesweeseeesw"),
        String::from("swswswswswswwswnwswswwswseswswswsw"),
        String::from("eneseseseswsesesewsesesesesenwseseswenese"),
        String::from("nenesweenenenewneneeeneswnweenene"),
        String::from("eneswsenwseenwenwene"),
        String::from("swsewnenwenwwwwseseseswnwwne"),
        String::from("seeseseseseseseswsewsesesenwseseseewse"),
        String::from("swenewswnenwswsweswneswswswse"),
        String::from("wnwwnwwwswwwwnwsenenwnwwwnwwww"),
        String::from("eswswwswswnwswswwwswswsewsweeswww"),
        String::from("nwwnwenwnwnwwnwsewnwwwnwnenwnwnwnwnw"),
        String::from("seswwseeswswseenwneseswnewwswseswsw"),
        String::from("enewwwswesewwnenwseswseweenwnwnew"),
        String::from("swseswseesenwseseseseseseseswseswwsee"),
        String::from("neneneneneneneneneneneenwnewneswe"),
        String::from("wnwswswnewnwnwwwsenewweeswnwnenww"),
        String::from("swenweenweeneswneeeeneneee"),
        String::from("nesweswswseeswswsenwswsewwseneneswse"),
        String::from("nwneswewnwnenwnwnenesenenenwnwnwneswnene"),
        String::from("wenwswnwnwnwnwnenwnwnwenenwnwnwnwnwnwnwne"),
        String::from("seseneesewnwnwneenwseeswswsesewnese"),
        String::from("swnewswnwswnwnwnwwenwnwseewnwnenenww"),
        String::from("seesesewenwneeeenwnesenenwsweseswnwsw"),
        String::from("swnenenwnwnwnenenwnwnwnwswnenenenenwnwse"),
        String::from("ewewnwwswesewsweswnweswswnwnwwnesw"),
        String::from("neseneewwswwwwnwwwewwwwwsww"),
        String::from("enwnwnwwswnesewwnwnwsewswnw"),
        String::from("sewwwwwsweswnwswswnwwwwewsesw"),
        String::from("neneneseweneenenwesewnenenenenenese"),
        String::from("eeeenweeeeswseewnweewneswnew"),
        String::from("wnwnenwnweneneswnenwenenenwnesenwne"),
        String::from("eseseseseswsenwseseswsesesesesesesesese"),
        String::from("eseeseeseeesesenwwseene"),
        String::from("nenwnwnwnewnwnesenwnwsenwnwneneseesw"),
        String::from("ewwnwnewnwwnwnwnwnwnwswswswwwnwenw"),
        String::from("senwwneeneeeneneneenewneswenwnene"),
        String::from("nwnenwnenwewenwnenewseeeenwswswwswe"),
        String::from("wwewwwwnwwnwwwnw"),
        String::from("eeeeeeseseeeeeeeeeew"),
        String::from("wnwneeeseeneeneeneeneweseeenesw"),
        String::from("nwwnwsweswwwseww"),
        String::from("swswwswneswseswswswseswswseswsesweswwsw"),
        String::from("newneneeneseenenenenenenenenenenewwne"),
        String::from("nesewwwwswwnwwwnwwwneewwwsee"),
        String::from("enwseseseseeseseseeeseesese"),
        String::from("seeseseseseseeseseswneseswseseesesesenwse"),
        String::from("nwseeseeesesewswseswwsenwseswneseesw"),
        String::from("wneseenwnenwenwneeneneneneneeseesee"),
        String::from("nwneesenwsweeneneneeseeneesenwww"),
        String::from("nenenwswnwswnwnwnwnwnwnenwnenenwnenwnwnwnw"),
        String::from("nwnwnwenwnwnwnwnwnwnwnwnewnenwnwswnwnw"),
        String::from("wwwwnwwnwwnwewnwnwnwwnwwwswnw"),
        String::from("neewneenewseneneeneneneneneneneene"),
        String::from("neneneneneneneneneneswnenwnenenwnesenwnene"),
        String::from("eeeeeeeseeeeeeeneeweee"),
        String::from("ewwsweswsweseswswswswnwnwewnwnesw"),
        String::from("weswswseseenweneesenenwnwnwneswswse"),
        String::from("nwswswseswwswswswswwwswsww"),
        String::from("seswseswwseseswswswneseswseswswswneseswswsw"),
        String::from("eneeneewnenwneeseeneneeneneneseeee"),
        String::from("eenwnweswenwenenwswswneeeewese"),
        String::from("nenenenesweneswneswnenwne"),
        String::from("enweseeseeneesweswnwsee"),
        String::from("swnesesenenwwswnwsesenweneenenweswwew"),
        String::from("nenwnwnwnwnwnwnwnwnwwnwnesenwswnwenwnw"),
        String::from("nwwnenwnwnwswnwswsenwnwenwnwswnwenwnwe"),
        String::from("swweeenwneswnwnwwswsewwswswseneew"),
        String::from("esewnwseenwseseenweseseseesesesenwse"),
        String::from("enweseeeeseseeneeseeeseweee"),
        String::from("eeseeeeseseseeeewneeeseeeswe"),
        String::from("swswwwnewswwswwswwswwswsw"),
        String::from("eewseeenwsweenweneesewnweew"),
        String::from("wswswsenweswnwsenwnwswswwneseweneww"),
        String::from("nenewswnenesenenenenenwnwnenewneenenene"),
        String::from("nwnwnwnwnwenenwnwnwwnwnwnw"),
        String::from("sweweesweseeeswnweenwseneeenwee"),
        String::from("ewesesenweseenwseseseeseneseeeswe"),
        String::from("eneenenewnenenenenesenenene"),
        String::from("eeeesesweeewseseeeneesewenesew"),
        String::from("wswwwswswswwswswnwsweswswwswnewseswsw"),
        String::from("swswswseswswswswswswswswswseseseswswenw"),
        String::from("neenenwenenweseweneenesenwswneswnwswne"),
        String::from("seswwwwwwwwwwwwwwwwnesenewne"),
        String::from("swswswswswsweswswseswswswswswswseenwnwswsw"),
        String::from("eneeeseeseseeseeseewseseseseee"),
        String::from("swneswswwnewewswswsewwswwswnewse"),
        String::from("wnwnwwwswwnwwewwwwwseewnewsw"),
        String::from("senweeneeseeewenwsew"),
        String::from("nwnwnwnwseswnwnwnwnwenwnwenwnwnwnwwwwsw"),
        String::from("eeseneeeswewenwneeseeeeeee"),
        String::from("wnwenwwnwnwnwnwe"),
        String::from("wswwswswwwwwwsewswwneswswswsww"),
        String::from("nwnwnwnwnenwnwnenenesw"),
        String::from("nenewwnwnwswnwesenwneseneenenwneewne"),
        String::from("nwneneswnwnenenwnwwsenwnenwnenenwnenenw"),
        String::from("swwwwswswnenwsweswenwswseneswwswnese"),
        String::from("eeeeewneweeeeswsewesweenwene"),
        String::from("seswsewnwwnenwwsesenesewnwweeswswnwse"),
        String::from("senweeseseswnewseseswsenesese"),
        String::from("nwsenwnwnwnwnwnwenwnwnwnwwnwwwnwww"),
        String::from("wseseseseseswswswswneswse"),
        String::from("nwneneswnenenenenwnenwne"),
        String::from("esenwseeswseseseseseseswsesenesenwswse"),
        String::from("seswswswswnenwswenewenwneswseswwswswswse"),
        String::from("sweswwwnwswwswwnweswww"),
        String::from("swwswsewswwswwswwswswwnewneww"),
        String::from("swseneswwnwweswswseswseeswwneswswswew"),
        String::from("eseseseesesesenweeseseseweeseswese"),
        String::from("swswnwnwnweswswswswswswswee"),
        String::from("swseneswsesenesweewwseneswseswswnwnw"),
        String::from("sewseeseseseeeseseesesesenese"),
        String::from("seswnesesesesesesewseseseswsesesesesese"),
        String::from("seseseseswseswseseseseswsesewseswsenese"),
        String::from("enwnenwenwnenwnwswsenwnwswne"),
        String::from("enenewnenwneneneneneneneewnenenenene"),
        String::from("nwwsweneswwswwsewswwswwswwenwswsw"),
        String::from("swsewseseneswswswseseswseeswseswsesese"),
        String::from("neneseewneseneneneeneneenwnenewe"),
        String::from("wwnwwwewswewwwwwwwswwswww"),
        String::from("eeswneneneneneneneeneneneswswnenenwnw"),
        String::from("nwnwnenenwnwsenwnwnenenwnenw"),
        String::from("eeseseseesenwseseeesesesewseseseseesw"),
        String::from("wewwwswwwswwwwwwswnwsewwnw"),
        String::from("nwwnwnwwwnwnwewnwnwwnwswswnwwnwe"),
        String::from("nenwnenwnwnenwnwnwswnwnwwnwnesenwnweswnenw"),
        String::from("wwneweenenwswnesesewnewswswwwse"),
        String::from("seswswsesesesewswseseseseseseneseswsese"),
        String::from("swswseswseseswseswseneeswswseswsesewse"),
        String::from("eneneenweeewnwesenenwseswseewwe"),
        String::from("swenenweeeneeeneewseeswenwee"),
        String::from("enesenewwwswseseswsese"),
        String::from("eswneseweneneeneneeenweneneeee"),
        String::from("eseseeseseeweswswenwneeeeneewne"),
        String::from("wnwwneenwwwwsenwwwwnwwwwww"),
        String::from("nwnweseenweewneswesweeeeeneew"),
        String::from("swswswwnewswwswseneswwwswwwswsww"),
        String::from("nenwswnwnwnwenwnwnwnenenwnwnenwnwnwnene"),
        String::from("nwnwwwwnwnwwnwnewnwnwnwnwsenwwww"),
        String::from("wswnwwseswwswwswwnwwewswsewswew"),
        String::from("wneeweneneneseneswnewnenesesenenwnee"),
        String::from("sesesesenwseswseswsesesesenwsewseneesese"),
        String::from("swseswsenwsweseswsewswsweswse"),
        String::from("nesesesweewwsweswseseswnwnwnwswsee"),
        String::from("nenwnenwnwnenenwneswseseenw"),
        String::from("sesenwswsenenwseswnew"),
        String::from("sewseseseseeseseseseseesesesesenwseseswse"),
        String::from("sewwenwnwnwwnenwnewswnwwwwnwwwnww"),
        String::from("nwnenesewnwnwnwnwnwnenwsenwnwnwnwnwnwnwnw"),
        String::from("nenwseneswnweseseswneweswnesenweewne"),
        String::from("sesenwseseseewseseewseneseesesesesw"),
        String::from("wwnwwnwnwwseswwnwenwnwwwnwnwewww"),
        String::from("seseswsenwseswswseswwneseswsese"),
        String::from("sweeswnenenenwneneenweeeneeeeene"),
        String::from("seseseseswneswseswseswsenwseseseswsese"),
        String::from("enenenenenenwnwnwnwnenesenenwnwneswnwnene"),
        String::from("swwsweswwswwwswswswsw"),
        String::from("wwswwnwsewswwnenwwwwwnwenwnww"),
        String::from("eenwnwseseseseeeeeeeeeweeswswe"),
        String::from("nwsenwnwnwnwnwnwnwnwnenwnwnenwwne"),
        String::from("swwswswsweswswswswwesweseswswswswsww"),
        String::from("seseesenwseweseeeseseewseseswsese"),
        String::from("nwseeeesweeeeeseeweeenweeee"),
        String::from("seeswneseseseseseswsesesesesesesesenw"),
        String::from("eswenewsenwwneeeneeneeneenenee"),
        String::from("wswenwnwenwwnenwwswesewseneweewsw"),
        String::from("sweswenwswnwswswnwnwwnweenenwnwe"),
        String::from("nwenweeswswwww"),
        String::from("nwneneneswnwnenenenwnwneneswnwnwnesenenene"),
        String::from("swseeesweeewsesenwweseenweenee"),
        String::from("nenwneswneswneneenesenesewnwnesenewnenene"),
        String::from("sewsesesesesesesenwseseeseneseewwsese"),
        String::from("seswswswswwswwneswwswswswswwswwwnw"),
        String::from("eeesenweeewseweeeswweneswnenw"),
        String::from("eeeeeneeeweseeweeeeeeee"),
        String::from("seswnesesewwseseeenesenewseswwnesw"),
        String::from("eeeeeeseeewseeeeeneseeee"),
        String::from("nwwwnwenwwswwnwenwwsenesenwwnw"),
        String::from("wwwwwwwwwsenwwnwwnwwnwwwsew"),
        String::from("seswswswseswseseswswswseswnwesenwseswsesw"),
        String::from("eneeneeneneeeeweneneneseweneee"),
        String::from("swwwwewswnwswewnwswwswwswwwswsw"),
        String::from("eswneseeneneewneswseeweeeneenwnenw"),
        String::from("swswnwwwseswnwnesewseswwnwswsenwswe"),
        String::from("swswswwsewnwwwewswwneswsewwwnw"),
        String::from("nwnwwnwnwwnwnwsenwnwnwnwnwnwseenwnwnwnw"),
        String::from("seseseewsesesesesesenenewsesesesesesesese"),
        String::from("nesenenenenenwnwwnwnenwnenenewneneneene"),
        String::from("wesesesenweseseseswseseswsenwswsesewse"),
        String::from("eseeswseeeswenweeseseeeneeee"),
        String::from("neswwnwwwwnwwwewwnwswwenwww"),
        String::from("nwswnwnenwnwnwnwnwnwnweswne"),
        String::from("nwwwsenwnwnwwnwsenenwswnenwwnwnewwse"),
        String::from("seenwseeenwweseeeweesweeeese"),
        String::from("swswsweswswswneswswseswswwwswswswswneswne"),
        String::from("ewwwswwwwswwwwnwwwwwswww"),
        String::from("seswsenwseseseswsesesese"),
        String::from("neneeswewnenwswneneseswenwseewenene"),
        String::from("swnwnwenenenwnwnwnwseenwnwsenenwnwwnw"),
        String::from("nwneswneneneneneneseneneswnenenwnenw"),
        String::from("nwnwnwnwnwnwsewnwnwseenwnwnwnenwnwswnww"),
        String::from("seswseseswseseswneswneswswseswswseswswsese"),
        String::from("wnwnwnwnwnwnwnwnenwnwnwnwnwnwsesenwnwnwnw"),
        String::from("seseseeesesewsenenwseweeseesesee"),
        String::from("nwnenwwweseswnwwwnewwswseneseww"),
        String::from("swnwseseseesesesesesewseneseseseseswsesw"),
        String::from("seseseseesewneseseseneseeeseseeswsese"),
        String::from("nwnwwnwnenwewwnwneseswwwwnwww"),
        String::from("esesesesewseseseseseeseesenwsesesese"),
        String::from("eswswnwswswneswswswseweseseswswswswne"),
        String::from("swneenenenenenwnenenenenenwnenwnesenene"),
        String::from("nwwswnwswswnwnenweeenenesenwwsenesw"),
        String::from("eeeeeeeeeenweeeeenwswswee"),
        String::from("nwnenenenwswnenenwnenenenw"),
        String::from("nwwwnwnwenwnwnwsenwwwnwwnwwnwnwnwnw"),
        String::from("ewneweseeseseseseese"),
        String::from("nwnenwnwnwnewsesenwnw"),
        String::from("nenenwnewnwnwnenwsenwswneenese"),
        String::from("wnwwwwwnwwwwnewsewwwnwwswwnenw"),
        String::from("enweseeeeseseeeee"),
        String::from("wesweseneswsewnewwneewenenenwnwse"),
        String::from("eseeswseeseeseseseseeseenweeee"),
        String::from("wnwnweweswsesenweseseseseseswewsese"),
        String::from("eeeneeseeenwseeeneenwseweeee"),
        String::from("esenwseswseswswseswseseseswseseseswswse"),
        String::from("wwseswnewwwswewwwswnewwwew"),
        String::from("eeeneeeeeeenweeseenweeswee"),
        String::from("sesenwneewswweneswnewsenenwenwswnw"),
        String::from("nwnwneseenenewewnenewswneesenenene"),
        String::from("swweswswwswswwnwwwswswwwswnwwesww"),
        String::from("swnenenenwneneenwnwnwnenesweswnwnenenwnw"),
        String::from("nenwnwwewwnwnwnwsewswneenwswswnwnw"),
        String::from("nwwwsewwnwnewnesewwwwnwnwnwnww"),
        String::from("wswwnwsenwswnweswweswswwwwenenw"),
        String::from("neswswswneseswwswwwsewswwswnwnwneesw"),
        String::from("newewwswwswwewwwwwwwwseswne"),
        String::from("neenenweesweneneeneneneneneneneenese"),
        String::from("eseseseeswseweenweseseeesesesesee"),
        String::from("swseswseswswswseswseswswswnwsw"),
        String::from("nenenenenenesewneewsenenenenenenenenene"),
        String::from("eeswneseenweseeeeeeseewsewseee"),
        String::from("nwewswswwswswwswswwswswswswswswnwse"),
        String::from("nwnwnwnwnwnenwnwnwnenwswnwnwnw"),
        String::from("eeeseeeeeeweenweseseseeese"),
        String::from("swswwwswnewsewswwwnwswswsenwswsesw"),
        String::from("seseswsesewsenesenesenw"),
        String::from("seseswswseneswswswneswseswswnwsesesesesese"),
        String::from("nwnwwnwnwnwenwnwnwnwnwnwnwnwnwnwnwnw"),
        String::from("neeneseeneneneneeneenewneneneswnenew"),
        String::from("nwsenwnwnwnwwnwsenwnwnwnwnwenwnwnw"),
        String::from("swswswnwswswswswneswneswswswswewseswnwsw"),
        String::from("seswneswswswswswswswseswswswswswswenwsw"),
        String::from("wwwwnewnewnewswwswwswwwseswww"),
        String::from("swenweswseswseneseswswsesewsese"),
        String::from("ewswseswwsewsweswwswwswsenenenesene"),
        String::from("swwnwnwnwseneseenenenwneswwwwwseswse"),
        String::from("nesweneneeseneneneneneenenenenenwnwnenee"),
        String::from("enwnwwwnwnwnwnwnwnwnwnenwsenwnwwwnwnw"),
        String::from("wwwwwswwwwwnwwwewwnew"),
        String::from("nenenesenenwnwswenwnwnenenwneneneneeswne"),
        String::from("eeneeneneesweeneneneneeeeewene"),
        String::from("eeseseenwnwsesesenwesenwesesesewese"),
        String::from("neeeeswswneeeeeeenweeene"),
        String::from("seseesewnesewseseeseseswseneseswnwsene"),
        String::from("sesesewseeeneeseeseseseseeseeese"),
        String::from("wswwnwwnewsewnwnwnwesewwnwnesene"),
        String::from("eseeneenenewnenenwseesenwnwnesewnene"),
        String::from("eseeneeswnwneesesewwneswewwneesw"),
        String::from("neneswseneenwnenenenewneneneneneneseneene"),
        String::from("sesesweseswsesesewseswsesewsesweswse"),
        String::from("sewsesesesesewseseseneseeseneesesese"),
        String::from("swwwenwwnwswnwnwneswwwnenwsewnwww"),
        String::from("swwswswseseswswnwseswswswswsweseswsesw"),
        String::from("senwenwnewweneneswswnwswwsenwenwenwnw"),
        String::from("nenwnenenenenenenenenwneneneneneneenwwsw"),
        String::from("wwnwwsewsewswnewsenwneesw"),
        String::from("nenwnwseswnwnwenwesewnwneeswswnwnwswnw"),
        String::from("nenwswnenenenenweneseneewseeneewswene"),
        String::from("esenwwsenenenewnwnwswnwnwnwwwwnwnwnww"),
        String::from("sesenweeeseseeeseseeseeeseswese"),
        String::from("neneneneneenenenewsenenenenenenenenene"),
        String::from("eeeseeeesweneneneeeeeenenwe"),
        String::from("eswwwwnwneewwswwnwwneswwseswswwsw"),
        String::from("wseseeeesesesesenweeneseseseseeee"),
        String::from("esesesenweeeeeweeeswenwne"),
        String::from("wwwwswneenwsww"),
        String::from("seseswseneswswswseswseswswsewswswswseese"),
        String::from("weseswseeeneseseewnweseesesesee"),
        String::from("swswswswswswswswneswswsw"),
        String::from("swwswswswswswswswwswswenwwswww"),
        String::from("nweneneneeeneneeneeseneneneneene"),
        String::from("swwswwwneneswswwswwswwseswnewswsw"),
        String::from("eeeewenwweeeesweeeee"),
        String::from("wnwseeewswswwwswsewwswnewnenew"),
        String::from("ewseneeswswneswenweswnwwwwneswwe"),
        String::from("eswseswnenwswseswwseseesesesenesesesw"),
        String::from("senweeseseesesesesesw"),
        String::from("nwsesesewsewnweweseseeseswsesesw"),
        String::from("sewwwseseswswneenewenenwsenwseww"),
        String::from("nwnenwnwneswswsenweswneneneenenenenene"),
        String::from("eswnweeeeneeseneeeswenweneenw"),
        String::from("wsenwnwwnwnwnwnwnwnwnwnwwnw"),
        String::from("nwnwenesewenwnwnwwwnwwnwnwwnwew"),
        String::from("nwsenwnenwnesenwnwnwnww"),
        String::from("wnewneswnwwsesenwwweweseneneww"),
        String::from("swseseseneeseswsewse"),
        String::from("nenwsenwnwsenenwwnwwnwnenwnesenwnwnwnw"),
        String::from("neswswswswnweewnenwswswswswswswseswswne"),
        String::from("nwseseseseseeeseseseeeeseeeswsese"),
        String::from("wnwnwnwwwenwsewnwnwwnwnwwnwnwnenw"),
        String::from("wwwwwnwwewnwww"),
        String::from("nwswswswswswswswswswswswswswneswseswneswsw"),
        String::from("nenesweneneeneneneneneeneneenenee"),
        String::from("swswswswswswwseswwswwswsweswswswnwwsw"),
        String::from("nwwewswwnwwwwnewwnw"),
        String::from("eeewenweeeseneeeseeeeeeeswe"),
        String::from("swswenweswseseswneswswswsewsesesenenww"),
        String::from("eeseeeeeeneswseseseeeweeeee"),
        String::from("eeeseseeeeeeeeseenwenenweswesw"),
        String::from("neswseswswseseseswsesw"),
        String::from("sesenwwseneesewseneseseewneswswneswne"),
        String::from("senenwswswwwsewwsenenwwenwewnew"),
        String::from("neeseeweeeneeenenweeseeeee"),
        String::from("nwswwswswswseswwswswswnewswswwswsesw"),
        String::from("swneeneneeneswnwsesesesewnwesewsesesw"),
        String::from("swswenwneneewneswwswswesesewsesw"),
        String::from("nwnwsenenwnenwsenwnwnenwneneeswwnenewnwnw"),
        String::from("swsenenewswswsewwnewwwnwsewswwsw"),
        String::from("swenenenwseseneweenene"),
        String::from("wswwswneswsewswswswswswswsw"),
        String::from("wsenwsenwwwsewwnwswwnenwwnwnwnwew"),
        String::from("nesweweeswwseseseseeeeneenwew"),
        String::from("wseseneswnwswseseswseswswsenwwswswswesw"),
        String::from("wwnwnwnewswenweswenwnwenwnwswnww"),
        String::from("seswneswswseswwseswswseneswswnweswswswsesw"),
        String::from("swwwnewswwswswwwwwsww"),
        String::from("enwswswneeneneeneneneeneee"),
        String::from("swswwswswswswswswswneswswswswswsw"),
        String::from("sweseneswwseeeneeenwnenweswnenwne"),
        String::from("eseeeeweneeseesewseswnewe"),
        String::from("enwesweseenwseseeeesweeeenese"),
        String::from("eswsweesenwenweeeeseeeeeenwee"),
        String::from("eeeesenweseeeeeesweeseeee"),
        String::from("wwseenenwnwwnwnwwwwnwswsenwwnwenw"),
        String::from("sesenwseseseeseseswseswseswseswnwsenwsese"),
        String::from("eeeeneeneswnenwee"),
        String::from("seswneseswseswnwswswesesewseswswswswsenwse"),
        String::from("nwnwwnwwenwnwnwnw"),
        String::from("eenenenwneneeswneeneneseneneenenene"),
        String::from("seeseseseswseseesesene"),
        String::from("seseseswseseswnwswswwseswsweseswsesesenw"),
        String::from("nenenenenenesenenwnenenenenenesenenenewnenw"),
        String::from("nwenwnenenwnwenwswnwnwnwnwnwnwneneswsw"),
        String::from("nwneswswnenenwnwnenwnenwnenwnwswnenwnwnw"),
        String::from("eneneneeeeneeeweneeneenene"),
        String::from("enenenenwnenenesenenenenewneenenenene"),
        String::from("seseseseseswsesesesesesesesesesewnenesese"),
        String::from("nwnwenwwnwenwwwenwnwnwnwwwnwwsw"),
        String::from("eeseeesweeeseeeseeeeewnwenee"),
        String::from("sweneneeneeeeneeewneneeneneenw"),
        String::from("nenewnwneseseneneenwwswneneenenwwse"),
        String::from("nwswwwwneswsewwswwneweweswnwsew"),
        String::from("swswnwswswsweswsesw"),
        String::from("nwwnwnwnenwnwnwswnwnwwnwnwnwnwwnwwew"),
        String::from("swwwwwswswwwwneswwswsewwwwsw"),
        String::from("seswsenenenewewnenenwnenewenenenenesee"),
        String::from("wwnwwewnwnwenwwnwnwwnwswwwsww"),
        String::from("wswswswswswswneswswseswswswswswswwswsw"),
        String::from("sweseeeeeeeeenwneneeeenweee"),
        String::from("eneneneeneneneswnenenenewenenenenwnesw"),
        String::from("swseeesewsenwswsesesw"),
        String::from("eeneneenenwneeneweswsweneneeene"),
        String::from("swseseseseseseseseseeeenwswseesesesenese"),
        String::from("eneweeneeneneseenenenewseeeneenew"),
        String::from("eeswswseenenwnewe"),
        String::from("ewenwwsesesesenwnwwesenenwnesesew"),
        String::from("wwwwnwwwwnwenwwwnwwwwsenww"),
        String::from("swnwsesewnenwsesesesene"),
        String::from("sewnenenenwneenewsenwnenewneeesesw"),
        String::from("swswswswswswswswseswnwswsww"),
        String::from("seswswsenwwswseswnesweseseswswseseesenwse"),
        String::from("eswswwswswnwseswswswswswsweswswswswsw"),
        String::from("nwnweswwnesenwnwnwnweswnwnwnw"),
        String::from("eswnewwswesewwwnwewwesenwnwwsww"),
        String::from("eswnwneneneeeeswnesewnesweeeee"),
        String::from("ewswwnwnwnwwwnwnw"),
        String::from("eeneneeeneneneeenweneesweswnese"),
        String::from("seswseseseswseneseseswweseseswswswseswsw"),
        String::from("nwnwnwnwnenwwwenwenwnwnwesenwwnwnw"),
        String::from("sewwnwwenwswnwnww"),
        String::from("wseneseswseseswswenwseseswswswswswwse"),
        String::from("seseeneseweneneswnwseenwswnenenenwnene"),
        String::from("nenewswnwseseneeneneneseneneneewnenw"),
        String::from("eneeeneeneeeeneeneweese"),
        String::from("wwewwswwwwwwswswwww"),
        String::from("seswseseseseseswseseneseswnesesesesese"),
        String::from("neneswseswnwwseswswswwswswsweswnwwswe"),
        String::from("newwswswswswwswswneeswnewswsewese"),
        String::from("eseeeseeseeeeeseewe"),
        String::from("enenewnenesesenewnwswsenesenenwneneneesw"),
        String::from("neeseeeeesesweseseseeseseenweese"),
        String::from("nweswswswswswseeneswwsewswswswswswe"),
        String::from("wwwwwwsenwwwnwwenewwwnwwsww"),
        String::from("swsesewnwswswswneweswswseeswswneswsew"),
        String::from("swseswswswswswswswnesweeswswswsenwswswnw"),
        String::from("eeeneseeneweneeeweeeneeneenee"),
        String::from("nwnwnwnwnwenwnwnwnwswnwenwnwnwnewnwswswnw"),
        String::from("nwwnenwwenwnwwwsenwnwnwswnwwneww"),
        String::from("senewswswnenenenwneeneneneneneeenenenene"),
        String::from("eeseseeseesesenweseeseeseewse"),
        String::from("neswnesenenwswnenwswnenwswnwneswswnewseee"),
        String::from("senwnwnenenwnwnwnenenwnwnenwnwnenene"),
        String::from("wwnwwwwwwwwsenewnwww"),
        String::from("nwnwnwnwwnwnenwnenwnwneneenwswenwnwse"),
        String::from("wwwwnwsewswswwswenwswwswswwwww"),
        String::from("nwwwwnwwswenwwwnwenwnwnwnwswnww"),
        String::from("nenwesenwewneneseeseenwenewnenee"),
    ]
}

fn main() {
    let input = get_input();
    println!("Part 1: {}", solve1(&input));
}
